//go:build windows || (unix && !darwin && !linux)

package record

import (
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/daviddwlee84/exp-cli/internal/pathx"
)

func TestCanonicalReplacementFailsClosedWithoutAtomicExchange(t *testing.T) {
	rootPath := t.TempDir()
	destination := filepath.Join(rootPath, "record.md")
	old := []byte("old canonical bytes\n")
	if err := os.WriteFile(destination, old, 0o644); err != nil {
		t.Fatal(err)
	}
	identity, err := os.Lstat(destination)
	if err != nil {
		t.Fatal(err)
	}
	err = AtomicWrite(rootPath, "record.md", []byte("new canonical bytes\n"), AtomicWriteOptions{Expected: identity, ExpectedContent: old})
	if !errors.Is(err, ErrAtomicCASUnsupported) {
		t.Fatalf("canonical replacement error = %v", err)
	}
	if got, readErr := os.ReadFile(destination); readErr != nil || string(got) != string(old) {
		t.Fatalf("canonical destination changed: %q, %v", got, readErr)
	}
}

func TestDerivedReplacementUsesPortableRootedRename(t *testing.T) {
	rootPath := t.TempDir()
	destination := filepath.Join(rootPath, "README.md")
	old := []byte("old generated bytes\n")
	newContent := []byte("new generated bytes\n")
	if err := os.WriteFile(destination, old, 0o644); err != nil {
		t.Fatal(err)
	}
	identity, err := os.Lstat(destination)
	if err != nil {
		t.Fatal(err)
	}
	canonical, err := pathx.Canonical(rootPath)
	if err != nil {
		t.Fatal(err)
	}
	root, err := pathx.OpenCanonicalRootNoSymlinks(canonical)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	if err := AtomicWriteDerivedRoot(root, "README.md", newContent, AtomicWriteOptions{Expected: identity, ExpectedContent: old}); err != nil {
		t.Fatalf("derived replacement: %v", err)
	}
	if got, readErr := os.ReadFile(destination); readErr != nil || string(got) != string(newContent) {
		t.Fatalf("derived destination = %q, %v", got, readErr)
	}
}
