package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/daviddwlee84/exp-cli/internal/execx"
	"github.com/daviddwlee84/exp-cli/internal/project"
	"github.com/daviddwlee84/exp-cli/internal/projection"
	"github.com/daviddwlee84/exp-cli/internal/provider"
	"github.com/daviddwlee84/exp-cli/internal/record"
	"github.com/daviddwlee84/exp-cli/internal/research"
	"github.com/daviddwlee84/exp-cli/internal/safex"
	"github.com/google/uuid"
)

type commandInvocation struct {
	stdout string
	stderr string
	err    error
}

type blockingClosableReader struct {
	startedOnce sync.Once
	closedOnce  sync.Once
	started     chan struct{}
	closed      chan struct{}
	finished    chan struct{}
}

func (reader *blockingClosableReader) Read([]byte) (int, error) {
	reader.startedOnce.Do(func() { close(reader.started) })
	<-reader.closed
	close(reader.finished)
	return 0, io.EOF
}

func (reader *blockingClosableReader) Close() error {
	reader.closedOnce.Do(func() { close(reader.closed) })
	return nil
}

func TestInitCreatesAllProjectionsIsIdempotentAndChecksDrift(t *testing.T) {
	repository := newGitRepository(t)
	fixedTime := time.Date(2026, 8, 29, 10, 11, 12, 0, time.UTC)
	generator, calls := uuidGeneratorSequence(t,
		"01a01e60-0000-7101-8000-000000000101",
	)
	app := NewApp(t.Context(), nil, nil, nil)
	app.Now = func() time.Time { return fixedTime }
	app.GenerateUUID = generator

	first := invokeCommand(t, app, "", "--start-dir", repository, "init", "--name", "Command Study", "--json")
	if first.err != nil {
		t.Fatalf("init error = %v, stderr = %q", first.err, first.stderr)
	}
	envelope := decodeEnvelope(t, first.stdout)
	if !envelope.OK || envelope.SchemaVersion != MachineSchema || *calls != 1 {
		t.Fatalf("first init envelope=%#v generator calls=%d", envelope, *calls)
	}
	var data initData
	decodeData(t, envelope, &data)
	if !data.Created || data.Project.Name != "Command Study" || len(data.Projections.Written) != 4 {
		t.Fatalf("first init data = %#v", data)
	}
	if data.Project.RepositoryRoot != repository || data.Project.Root != filepath.Join(repository, "experiments") {
		t.Fatalf("safe project paths changed: %#v", data.Project)
	}
	for _, name := range projection.Paths() {
		content, err := os.ReadFile(filepath.Join(data.Project.Root, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		if !bytes.HasPrefix(content, []byte("<!-- Generated by exp render; DO NOT EDIT. -->\n")) {
			t.Fatalf("%s is not a generated projection: %q", name, content)
		}
	}

	second := invokeCommand(t, app, "", "--start-dir", filepath.Join(repository, "experiments"), "init", "--name", "Ignored", "--json")
	if second.err != nil {
		t.Fatal(second.err)
	}
	secondEnvelope := decodeEnvelope(t, second.stdout)
	decodeData(t, secondEnvelope, &data)
	if data.Created || data.Project.Name != "Command Study" || data.Projections.Changed || *calls != 1 {
		t.Fatalf("idempotent init data=%#v calls=%d", data, *calls)
	}

	readme := filepath.Join(data.Project.Root, projection.READMEFile)
	if err := os.WriteFile(readme, []byte("stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	before, err := os.ReadFile(readme)
	if err != nil {
		t.Fatal(err)
	}
	checked := invokeCommand(t, app, "", "--start-dir", repository, "render", "--check", "--json")
	if !errors.Is(checked.err, projection.ErrStale) {
		t.Fatalf("render --check error = %v", checked.err)
	}
	checkedEnvelope := decodeEnvelope(t, checked.stdout)
	if checkedEnvelope.OK || len(checkedEnvelope.Diagnostics) != 1 || checkedEnvelope.Diagnostics[0].Path != projection.READMEFile {
		t.Fatalf("stale envelope = %#v", checkedEnvelope)
	}
	var checkedData renderData
	decodeData(t, checkedEnvelope, &checkedData)
	if !reflect.DeepEqual(checkedData.Result.Drifted, []string{projection.READMEFile}) || checkedData.Result.Changed || len(checkedData.Result.Written) != 0 {
		t.Fatalf("stale result = %#v", checkedData.Result)
	}
	afterCheck, err := os.ReadFile(readme)
	if err != nil || !bytes.Equal(before, afterCheck) {
		t.Fatalf("render --check wrote README: %q, %v", afterCheck, err)
	}

	repaired := invokeCommand(t, app, "", "--start-dir", repository, "render", "--json")
	if repaired.err != nil {
		t.Fatal(repaired.err)
	}
	repairedEnvelope := decodeEnvelope(t, repaired.stdout)
	var repairedData renderData
	decodeData(t, repairedEnvelope, &repairedData)
	if !repairedData.Result.Current || !reflect.DeepEqual(repairedData.Result.Written, []string{projection.READMEFile}) {
		t.Fatalf("render repair = %#v", repairedData.Result)
	}
}

func TestProjectJSONRedactsCredentialShapedAbsolutePaths(t *testing.T) {
	const canary = "cli-project-path-canary-820d"
	credentialComponent := "auth_value=" + canary
	base, err := os.MkdirTemp("", "exp-project-path-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(base) })
	repository := filepath.Join(base, credentialComponent, "repo")
	if err := os.MkdirAll(repository, 0o755); err != nil {
		t.Fatal(err)
	}
	gitInit := exec.Command("git", "init", "--quiet")
	gitInit.Dir = repository
	if output, err := gitInit.CombinedOutput(); err != nil {
		t.Fatalf("git init: %v\n%s", err, output)
	}
	canonical, err := filepath.EvalSymlinks(repository)
	if err != nil {
		t.Fatal(err)
	}
	repository = canonical
	expectedRepository := strings.Replace(repository, credentialComponent, safex.Redacted, 1)
	if expectedRepository == repository {
		t.Fatalf("test repository %q does not contain credential component", repository)
	}

	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("USERPROFILE", home)
	app := deterministicApp(t, "01a01e60-0000-7101-8000-000000000101")
	for _, testCase := range []struct {
		name string
		args []string
	}{
		{name: "init", args: []string{"--start-dir", repository, "init", "--name", "Path Privacy", "--json"}},
		{name: "list", args: []string{"--start-dir", repository, "plan", "list", "--json"}},
		{name: "context", args: []string{"--start-dir", repository, "context", "--json"}},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			invocation := invokeCommand(t, app, "", testCase.args...)
			requireCommandSuccess(t, invocation)
			if strings.Contains(invocation.stdout, canary) {
				t.Fatalf("%s JSON leaked credential-shaped path: %s", testCase.name, invocation.stdout)
			}
			var data struct {
				Project projectView `json:"project"`
			}
			decodeData(t, decodeEnvelope(t, invocation.stdout), &data)
			if data.Project.RepositoryRoot != expectedRepository || data.Project.Root != filepath.Join(expectedRepository, "experiments") {
				t.Fatalf("%s project paths = %#v, want repository %q", testCase.name, data.Project, expectedRepository)
			}
		})
	}
}

func TestInitRefusesLegacyAndUnrelatedRootsWithJSONFailure(t *testing.T) {
	for name, existing := range map[string]string{"legacy": "REPORT.md", "unrelated": "notes.txt"} {
		t.Run(name, func(t *testing.T) {
			repository := newGitRepository(t)
			root := filepath.Join(repository, "experiments")
			if err := os.Mkdir(root, 0o755); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(root, existing)
			original := []byte("preserve exactly\n")
			if err := os.WriteFile(path, original, 0o640); err != nil {
				t.Fatal(err)
			}
			app := deterministicApp(t, "01a01e60-0000-7101-8000-000000000101")
			invocation := invokeCommand(t, app, "", "--start-dir", repository, "init", "--json")
			if invocation.err == nil {
				t.Fatal("init unexpectedly succeeded")
			}
			envelope := decodeEnvelope(t, invocation.stdout)
			if envelope.OK || envelope.SchemaVersion != MachineSchema || !bytes.Contains([]byte(invocation.stdout), []byte(`"diagnostics":[{`)) {
				t.Fatalf("failure envelope = %#v\n%s", envelope, invocation.stdout)
			}
			after, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(after, original) {
				t.Fatalf("existing root changed: %q, %v", after, err)
			}
			if _, err := os.Lstat(filepath.Join(root, record.ProjectFile)); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("PROJECT.md was written: %v", err)
			}
		})
	}
}

func TestPlanAddFlagsAndExactStdinRequestThenCanonicalList(t *testing.T) {
	repository := newGitRepository(t)
	app := deterministicApp(t,
		"01a01e60-0000-7101-8000-000000000101",
		"01a01e70-0000-7202-8000-000000000202",
		"01a01e71-0000-7303-8000-000000000303",
	)
	requireCommandSuccess(t, invokeCommand(t, app, "", "--start-dir", repository, "init", "--name", "Plan Commands", "--json"))

	flagResult := invokeCommand(t, app, "", "--start-dir", repository, "plan", "add",
		"--title", "Lower priority first ID",
		"--priority", "P2",
		"--effort", "M",
		"--payoff-summary", "Measure a bounded gain",
		"--payoff-metric", "macro_f1",
		"--payoff-unit", "score",
		"--payoff-estimate", "0",
		"--tags", "encoder,calibration",
		"--json",
	)
	requireCommandSuccess(t, flagResult)
	flagEnvelope := decodeEnvelope(t, flagResult.stdout)
	var flagData planAddData
	decodeData(t, flagEnvelope, &flagData)
	if flagData.Plan.ID != "plan_01a01e70-0000-7202-8000-000000000202" || flagData.Plan.Display != "P-01A01E70" || !record.ValidRevision(flagData.Plan.Revision) {
		t.Fatalf("flag Plan result = %#v", flagData.Plan)
	}
	if !strings.HasPrefix(flagData.Plan.Path, "experiments/plans/") || flagData.Plan.ExpectedPayoff.Estimate == nil || *flagData.Plan.ExpectedPayoff.Estimate != 0 {
		t.Fatalf("flag Plan path/payoff = %#v", flagData.Plan)
	}
	createdBytes, err := os.ReadFile(filepath.Join(repository, filepath.FromSlash(flagData.Plan.Path)))
	if err != nil {
		t.Fatal(err)
	}
	createdDocument, err := record.Decode(createdBytes)
	if err != nil {
		t.Fatal(err)
	}
	if got := createdDocument.Body; got != "\n# Lower priority first ID\n" {
		t.Fatalf("default Plan body = %q", got)
	}

	request := `{
		"schema_version":"exp.request.plan-add/v1",
		"title":"High priority JSON Plan",
		"body":"\n# JSON body\n\nExact input.\n",
		"priority":"P1",
		"effort":"S",
		"expected_payoff":{"summary":"Improve score","metric":"macro_f1","unit":"score","estimate":0.03},
		"tags":["json"],
		"assumptions":[]
	}`
	stdinResult := invokeCommand(t, app, request, "--start-dir", repository, "plan", "add", "--input", "-", "--json")
	requireCommandSuccess(t, stdinResult)
	stdinEnvelope := decodeEnvelope(t, stdinResult.stdout)
	var stdinData planAddData
	decodeData(t, stdinEnvelope, &stdinData)
	if stdinData.Plan.ID != "plan_01a01e71-0000-7303-8000-000000000303" || stdinData.Plan.Title != "High priority JSON Plan" {
		t.Fatalf("stdin Plan = %#v", stdinData.Plan)
	}

	roadmap := filepath.Join(repository, "experiments", projection.RoadmapFile)
	if err := os.WriteFile(roadmap, []byte("not canonical and intentionally stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	listed := invokeCommand(t, app, "", "--start-dir", repository, "plan", "list", "--json")
	requireCommandSuccess(t, listed)
	listedEnvelope := decodeEnvelope(t, listed.stdout)
	var listedData planListData
	decodeData(t, listedEnvelope, &listedData)
	if got, want := len(listedData.Plans), 2; got != want {
		t.Fatalf("listed Plans = %d, want %d", got, want)
	}
	if listedData.Plans[0].Priority != "P1" || listedData.Plans[0].ID != stdinData.Plan.ID || listedData.Plans[1].ID != flagData.Plan.ID {
		t.Fatalf("canonical list ordering = %#v", listedData.Plans)
	}
	for _, plan := range listedData.Plans {
		if plan.ID == "" || plan.Display == "" || !record.ValidRevision(plan.Revision) {
			t.Errorf("list omitted identity/revision: %#v", plan)
		}
	}
}

func TestConcurrentPlanAddsLeaveProjectionsCurrent(t *testing.T) {
	repository := newGitRepository(t)
	initializer := deterministicApp(t, "01a01e60-0000-7101-8000-000000000101")
	requireCommandSuccess(t, invokeCommand(t, initializer, "", "--start-dir", repository, "init", "--json"))

	first := deterministicApp(t, "01a01e75-0000-7707-8000-000000000707")
	second := deterministicApp(t, "01a01e76-0000-7808-8000-000000000808")
	results := make(chan commandInvocation, 2)
	add := func(app *App, title string) {
		results <- invokeCommand(t, app, "", "--start-dir", repository, "plan", "add",
			"--title", title, "--priority", "P1", "--effort", "S",
			"--payoff-summary", "Concurrent value", "--payoff-metric", "score", "--payoff-unit", "score", "--json")
	}
	go add(first, "Concurrent first")
	go add(second, "Concurrent second")
	for range 2 {
		result := <-results
		if result.err != nil {
			t.Fatalf("concurrent plan add failed: %v, stdout=%s", result.err, result.stdout)
		}
	}
	inventory, err := record.LoadInventory(filepath.Join(repository, "experiments"))
	if err != nil {
		t.Fatal(err)
	}
	if plans := inventory.OfKind(research.KindPlan); len(plans) != 2 {
		t.Fatalf("concurrent Plan count = %d", len(plans))
	}
	checked, err := projection.Check(t.Context(), inventory)
	if err != nil || !checked.Current {
		t.Fatalf("concurrent projections are stale: %#v, %v", checked, err)
	}
}

func TestPlanAddKeepsCanonicalCreationWhenProjectionRefreshFails(t *testing.T) {
	repository := newGitRepository(t)
	app := deterministicApp(t,
		"01a01e60-0000-7101-8000-000000000101",
		"01a01e74-0000-7606-8000-000000000606",
	)
	requireCommandSuccess(t, invokeCommand(t, app, "", "--start-dir", repository, "init", "--json"))
	sentinel := errors.New("injected projection failure")
	app.RenderProjections = func(context.Context, *record.Inventory) (projection.Result, error) {
		return projection.Result{}, sentinel
	}
	invocation := invokeCommand(t, app, "", "--start-dir", repository, "plan", "add",
		"--title", "Durable before projection", "--priority", "P1", "--effort", "S",
		"--payoff-summary", "Prove publication", "--payoff-metric", "score", "--payoff-unit", "score", "--json")
	if !errors.Is(invocation.err, sentinel) {
		t.Fatalf("projection failure error = %v", invocation.err)
	}
	envelope := decodeEnvelope(t, invocation.stdout)
	var data planAddData
	decodeData(t, envelope, &data)
	if envelope.OK || !envelope.Partial || data.Plan.ID != "plan_01a01e74-0000-7606-8000-000000000606" || data.Projections.Written == nil {
		t.Fatalf("partial Plan result = envelope %#v data %#v", envelope, data)
	}
	inventory, err := record.LoadInventory(filepath.Join(repository, "experiments"))
	if err != nil {
		t.Fatal(err)
	}
	if plans := inventory.OfKind(research.KindPlan); len(plans) != 1 {
		t.Fatalf("canonical Plan was rolled back after projection failure: %d", len(plans))
	}
}

func TestInitPreservesPublishedIdentityWhenDurabilityIsUncertain(t *testing.T) {
	repository := newGitRepository(t)
	app := deterministicApp(t, "01a01e60-0000-7101-8000-000000000101")
	sentinel := errors.New("injected directory sync failure")
	app.InitializeProject = func(ctx context.Context, request project.InitRequest) (*project.Info, bool, error) {
		return project.Initialize(ctx, request,
			project.WithClock(app.clock),
			project.WithUUIDGenerator(app.GenerateUUID),
			project.WithAtomicHook(func(stage record.AtomicStage, destination string) error {
				if stage == record.StageDirSync && destination == record.ProjectFile {
					return sentinel
				}
				return nil
			}),
		)
	}

	invocation := invokeCommand(t, app, "", "--start-dir", repository, "init", "--name", "Published Project", "--json")
	if !errors.Is(invocation.err, sentinel) {
		t.Fatalf("init error = %v, want injected durability failure", invocation.err)
	}
	envelope := decodeEnvelope(t, invocation.stdout)
	var data initData
	decodeData(t, envelope, &data)
	if envelope.OK || !envelope.Partial || !data.Created || data.Project.ID != "01a01e60-0000-7101-8000-000000000101" {
		t.Fatalf("published init result = envelope %#v data %#v", envelope, data)
	}
	if len(envelope.Diagnostics) != 1 || envelope.Diagnostics[0].Code != "publication.durability_uncertain" || !strings.Contains(envelope.Diagnostics[0].Message, "canonical bytes were published") {
		t.Fatalf("published init diagnostics = %#v", envelope.Diagnostics)
	}
	if data.Projections.Written == nil || data.Projections.Drifted == nil {
		t.Fatalf("published init has unstable projection data = %#v", data.Projections)
	}
	if _, err := os.Stat(filepath.Join(repository, "experiments", record.ProjectFile)); err != nil {
		t.Fatalf("published PROJECT.md is absent: %v", err)
	}
}

func TestPlanAddPreservesPublishedIdentityWhenDurabilityIsUncertain(t *testing.T) {
	repository := newGitRepository(t)
	app := deterministicApp(t,
		"01a01e60-0000-7101-8000-000000000101",
		"01a01e74-0000-7606-8000-000000000606",
	)
	requireCommandSuccess(t, invokeCommand(t, app, "", "--start-dir", repository, "init", "--json"))
	sentinel := errors.New("injected directory sync failure")
	app.NewStore = func(info *project.Info) (RecordStore, error) {
		return record.NewStore(info.Root, info.Repository.GitCommonDir,
			record.WithClock(app.clock),
			record.WithUUIDGenerator(app.GenerateUUID),
			record.WithAtomicHook(func(stage record.AtomicStage, destination string) error {
				if stage == record.StageDirSync && strings.HasPrefix(destination, "plans/") {
					return sentinel
				}
				return nil
			}),
		), nil
	}

	invocation := invokeCommand(t, app, "", "--start-dir", repository, "plan", "add",
		"--title", "Published before fsync", "--priority", "P1", "--effort", "S",
		"--payoff-summary", "Preserve identity", "--payoff-metric", "score", "--payoff-unit", "score", "--json")
	if !errors.Is(invocation.err, sentinel) {
		t.Fatalf("plan add error = %v, want injected durability failure", invocation.err)
	}
	envelope := decodeEnvelope(t, invocation.stdout)
	var data planAddData
	decodeData(t, envelope, &data)
	if envelope.OK || !envelope.Partial || data.Plan.ID != "plan_01a01e74-0000-7606-8000-000000000606" || data.Plan.Path == "" || data.Plan.Revision == "" {
		t.Fatalf("published Plan result = envelope %#v data %#v", envelope, data)
	}
	if len(envelope.Diagnostics) != 1 || envelope.Diagnostics[0].Code != "publication.durability_uncertain" || !strings.Contains(envelope.Diagnostics[0].Message, "canonical bytes were published") {
		t.Fatalf("published Plan diagnostics = %#v", envelope.Diagnostics)
	}
	inventory, err := record.LoadInventory(filepath.Join(repository, "experiments"))
	if err != nil || len(inventory.OfKind(research.KindPlan)) != 1 {
		t.Fatalf("published Plan inventory = %#v, %v", inventory, err)
	}
}

func TestRenderFailureDerivesPartialFromPublishedFiles(t *testing.T) {
	repository := newGitRepository(t)
	app := deterministicApp(t, "01a01e60-0000-7101-8000-000000000101")
	requireCommandSuccess(t, invokeCommand(t, app, "", "--start-dir", repository, "init", "--json"))
	roadmap := filepath.Join(repository, "experiments", projection.RoadmapFile)
	if err := os.WriteFile(roadmap, []byte("stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	sentinel := errors.New("injected projection directory sync failure")
	app.RenderProjections = func(ctx context.Context, inventory *record.Inventory) (projection.Result, error) {
		return projection.RenderWithOptions(ctx, inventory, projection.RenderOptions{AtomicHook: func(stage record.AtomicStage, destination string) error {
			if stage == record.StageDirSync && destination == projection.RoadmapFile {
				return sentinel
			}
			return nil
		}})
	}
	invocation := invokeCommand(t, app, "", "--start-dir", repository, "render", "--json")
	if !errors.Is(invocation.err, sentinel) {
		t.Fatalf("render error = %v", invocation.err)
	}
	envelope := decodeEnvelope(t, invocation.stdout)
	var data renderData
	decodeData(t, envelope, &data)
	if envelope.OK || !envelope.Partial || !reflect.DeepEqual(data.Result.Written, []string{projection.RoadmapFile}) || !data.Result.Current || len(data.Result.Drifted) != 0 {
		t.Fatalf("partial render result = envelope %#v data %#v", envelope, data)
	}
	if len(envelope.Diagnostics) != 1 || envelope.Diagnostics[0].Code != "publication.durability_uncertain" || envelope.Diagnostics[0].Path != projection.RoadmapFile || !strings.Contains(envelope.Diagnostics[0].Message, "generated projection bytes were published") {
		t.Fatalf("render durability failure diagnostics = %#v", envelope.Diagnostics)
	}
	inventory, err := record.LoadInventory(filepath.Join(repository, "experiments"))
	if err != nil {
		t.Fatal(err)
	}
	checked, err := projection.Check(t.Context(), inventory)
	if err != nil || !checked.Current {
		t.Fatalf("published projection bytes were reported current afterward: %#v, %v", checked, err)
	}
}

func TestPlanAddRejectsUnknownTrailingMixedAndInvalidInputsWithPureJSON(t *testing.T) {
	repository := newGitRepository(t)
	app := deterministicApp(t,
		"01a01e60-0000-7101-8000-000000000101",
		"01a01e72-0000-7404-8000-000000000404",
		"01a01e72-0000-7404-8000-000000000404",
		"01a01e72-0000-7404-8000-000000000404",
	)
	requireCommandSuccess(t, invokeCommand(t, app, "", "--start-dir", repository, "init", "--json"))
	valid := `{"schema_version":"exp.request.plan-add/v1","title":"Plan","priority":"P1","effort":"S","expected_payoff":{"summary":"Gain","metric":"score","unit":"score"}}`
	tests := []struct {
		name  string
		input string
		args  []string
	}{
		{name: "unknown top-level field", input: strings.Replace(valid, `"title":"Plan"`, `"title":"Plan","unknown":true`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "unknown nested field", input: strings.Replace(valid, `"unit":"score"`, `"unit":"score","unknown":true`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "case-variant top-level field", input: strings.Replace(valid, `"title":"Plan"`, `"Title":"Plan"`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "case-variant nested field", input: strings.Replace(valid, `"summary":"Gain"`, `"Summary":"Gain"`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "duplicate field", input: strings.Replace(valid, `"title":"Plan"`, `"title":"Plan","title":"Again"`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "semantic duplicate field", input: strings.Replace(valid, `"title":"Plan"`, `"title":"Plan","Title":"Again"`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "escaped duplicate field", input: strings.Replace(valid, `"title":"Plan"`, `"title":"Plan","t`+string(rune(92))+`u0069tle":"Again"`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "invalid UTF-8", input: strings.Replace(valid, "Plan", "bad-\xff-title", 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "oversized input", input: strings.Repeat(" ", maxPlanRequestBytes+1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "trailing JSON", input: valid + `{}`, args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "old schema field", input: strings.Replace(valid, `"schema_version"`, `"schema"`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "mixed modes", input: valid, args: []string{"plan", "add", "--input", "-", "--title", "mixed", "--json"}},
		{name: "non-stdin input", input: valid, args: []string{"plan", "add", "--input", "request.json", "--json"}},
		{name: "explicit empty body", input: strings.Replace(valid, `"title":"Plan"`, `"title":"Plan","body":""`, 1), args: []string{"plan", "add", "--input", "-", "--json"}},
		{name: "missing assumption", args: []string{"plan", "add", "--title", "Missing assumption", "--priority", "P1", "--effort", "S", "--payoff-summary", "Gain", "--payoff-metric", "score", "--payoff-unit", "score", "--assumptions", "F-FFFFFFFF", "--json"}},
		{name: "invalid finite estimate", args: []string{"plan", "add", "--title", "Bad estimate", "--priority", "P1", "--effort", "S", "--payoff-summary", "Gain", "--payoff-metric", "score", "--payoff-unit", "score", "--payoff-estimate", "NaN", "--json"}},
		{name: "invalid tag", args: []string{"plan", "add", "--title", "Bad tag", "--priority", "P1", "--effort", "S", "--payoff-summary", "Gain", "--payoff-metric", "score", "--payoff-unit", "score", "--tags", "Uppercase", "--json"}},
		{name: "missing required fields", args: []string{"plan", "add", "--title", "Incomplete", "--json"}},
	}
	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			args := append([]string{"--start-dir", repository}, testCase.args...)
			invocation := invokeCommand(t, app, testCase.input, args...)
			if invocation.err == nil {
				t.Fatal("invalid plan add unexpectedly succeeded")
			}
			envelope := decodeEnvelope(t, invocation.stdout)
			if envelope.OK || envelope.SchemaVersion != MachineSchema || len(envelope.Diagnostics) == 0 {
				t.Fatalf("failure envelope = %#v", envelope)
			}
			if strings.Contains(strings.ToLower(invocation.stdout), "prompt") || !strings.HasSuffix(invocation.stdout, "\n") {
				t.Fatalf("machine failure output is contaminated: %q", invocation.stdout)
			}
		})
	}
	listed := invokeCommand(t, app, "", "--start-dir", repository, "plan", "list", "--json")
	requireCommandSuccess(t, listed)
	var data planListData
	decodeData(t, decodeEnvelope(t, listed.stdout), &data)
	if len(data.Plans) != 0 {
		t.Fatalf("invalid requests published Plans: %#v", data.Plans)
	}
}

func TestValidateInvalidCanonicalFixtureReportsOneFailureEnvelope(t *testing.T) {
	repository := newGitRepository(t)
	root := filepath.Join(repository, "experiments")
	if err := os.CopyFS(root, os.DirFS(validFixtureRoot(t))); err != nil {
		t.Fatal(err)
	}
	planPath := filepath.Join(root, "plans", "plan_01a01e66-f8e0-7202-8000-000000000202-calibrate-encoder-learning-rate.md")
	content, err := os.ReadFile(planPath)
	if err != nil {
		t.Fatal(err)
	}
	content = bytes.Replace(content, []byte("priority = \"P1\"\n"), []byte("priority = \"P1\"\nunknown_cli_field = true\n"), 1)
	if err := os.WriteFile(planPath, content, 0o644); err != nil {
		t.Fatal(err)
	}
	app := deterministicApp(t)
	invocation := invokeCommand(t, app, "", "--start-dir", repository, "validate", "--json")
	if invocation.err == nil {
		t.Fatal("invalid fixture validated")
	}
	envelope := decodeEnvelope(t, invocation.stdout)
	var data validateData
	decodeData(t, envelope, &data)
	if envelope.OK || data.Valid || len(envelope.Diagnostics) == 0 || envelope.Diagnostics[0].Code != "record.unknown_field" {
		t.Fatalf("validation failure = envelope %#v data %#v", envelope, data)
	}
	if strings.Contains(invocation.stdout, "exp:") || !bytes.Contains([]byte(invocation.stdout), []byte(`"diagnostics":[`)) {
		t.Fatalf("JSON stdout contamination: %q", invocation.stdout)
	}

	human := invokeCommand(t, app, "", "--start-dir", repository, "validate")
	if human.err == nil || !strings.Contains(human.stdout, "ERROR ") || !strings.Contains(human.stdout, "record.unknown_field") {
		t.Fatalf("human validation output = %q, %v", human.stdout, human.err)
	}
}

func TestContextIsLocalOnlyAndExposesNoRefreshSignal(t *testing.T) {
	repository := newGitRepository(t)
	app := deterministicApp(t,
		"01a01e60-0000-7101-8000-000000000101",
		"01a01e73-0000-7505-8000-000000000505",
	)
	requireCommandSuccess(t, invokeCommand(t, app, "", "--start-dir", repository, "init", "--json"))
	requireCommandSuccess(t, invokeCommand(t, app, "", "--start-dir", repository, "plan", "add",
		"--title", "Local queue", "--priority", "P1", "--effort", "S",
		"--payoff-summary", "Bound learning", "--payoff-metric", "score", "--payoff-unit", "score", "--json"))

	registry := &countingProviderRegistry{}
	providerCalls := 0
	app.Registry = registry
	app.Invoker = execx.InvokerFunc(func(context.Context, execx.CommandSpec) (execx.Result, error) {
		providerCalls++
		return execx.Result{}, errors.New("context must not invoke providers")
	})
	result := invokeCommand(t, app, "", "--start-dir", repository, "context", "--json")
	requireCommandSuccess(t, result)
	var data contextData
	decodeData(t, decodeEnvelope(t, result.stdout), &data)
	if data.ProviderRefresh || data.LiveObservations || data.ObservationScope != "local_canonical_records_only" || len(data.QueuedPlans) != 1 {
		t.Fatalf("context data = %#v", data)
	}
	if registry.calls != 0 || providerCalls != 0 {
		t.Fatalf("context called registry=%d invoker=%d", registry.calls, providerCalls)
	}
}

func TestPlanInputCancellationClosesClosableReaderWithoutLeakingRead(t *testing.T) {
	reader := &blockingClosableReader{
		started:  make(chan struct{}),
		closed:   make(chan struct{}),
		finished: make(chan struct{}),
	}
	ctx, cancel := context.WithCancel(t.Context())
	completed := make(chan error, 1)
	go func() {
		_, err := decodePlanAddRequest(ctx, reader)
		completed <- err
	}()
	<-reader.started
	cancel()
	select {
	case err := <-completed:
		if !errors.Is(err, context.Canceled) {
			t.Fatalf("decodePlanAddRequest() error = %v", err)
		}
	case <-time.After(time.Second):
		t.Fatal("canceled Plan input did not return")
	}
	select {
	case <-reader.finished:
	case <-time.After(time.Second):
		t.Fatal("closable Plan input left its reader blocked")
	}
}

func TestCanceledJSONCommandUsesRootContextAndOneEnvelope(t *testing.T) {
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	app := NewApp(ctx, nil, nil, nil)
	app.DiscoverProject = func(got context.Context, _ string) (*project.Info, error) {
		if !errors.Is(got.Err(), context.Canceled) {
			t.Fatalf("discovery context error = %v", got.Err())
		}
		return nil, got.Err()
	}
	invocation := invokeCommand(t, app, "", "validate", "--json")
	if !errors.Is(invocation.err, context.Canceled) {
		t.Fatalf("canceled command error = %v", invocation.err)
	}
	envelope := decodeEnvelope(t, invocation.stdout)
	if envelope.OK || len(envelope.Diagnostics) != 1 || envelope.Diagnostics[0].Code != "command.canceled" {
		t.Fatalf("canceled envelope = %#v", envelope)
	}
}

type rawEnvelope struct {
	SchemaVersion string          `json:"schema_version"`
	Command       string          `json:"command"`
	OK            bool            `json:"ok"`
	Partial       bool            `json:"partial"`
	ObservedAt    string          `json:"observed_at"`
	Data          json.RawMessage `json:"data"`
	Diagnostics   []Diagnostic    `json:"diagnostics"`
}

func invokeCommand(t *testing.T, app *App, input string, args ...string) commandInvocation {
	t.Helper()
	var stdout, stderr bytes.Buffer
	app.In = strings.NewReader(input)
	app.Out = &stdout
	app.Err = &stderr
	root := NewRootCommand(app)
	root.SetArgs(args)
	err := root.ExecuteContext(app.Context)
	return commandInvocation{stdout: stdout.String(), stderr: stderr.String(), err: err}
}

func decodeEnvelope(t *testing.T, output string) rawEnvelope {
	t.Helper()
	decoder := json.NewDecoder(strings.NewReader(output))
	var envelope rawEnvelope
	if err := decoder.Decode(&envelope); err != nil {
		t.Fatalf("decode envelope %q: %v", output, err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		t.Fatalf("machine stdout has trailing content %q: %v", output, err)
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal([]byte(output), &fields); err != nil {
		t.Fatal(err)
	}
	if _, old := fields["schema"]; old {
		t.Fatalf("machine envelope supports obsolete schema field: %s", output)
	}
	if envelope.SchemaVersion != MachineSchema || envelope.Diagnostics == nil || !strings.Contains(output, `"diagnostics":[`) {
		t.Fatalf("unstable machine envelope = %#v\n%s", envelope, output)
	}
	return envelope
}

func decodeData(t *testing.T, envelope rawEnvelope, destination any) {
	t.Helper()
	if err := json.Unmarshal(envelope.Data, destination); err != nil {
		t.Fatalf("decode %s data %s: %v", envelope.Command, envelope.Data, err)
	}
}

func requireCommandSuccess(t *testing.T, invocation commandInvocation) {
	t.Helper()
	if invocation.err != nil {
		t.Fatalf("command error = %v, stdout=%q stderr=%q", invocation.err, invocation.stdout, invocation.stderr)
	}
	envelope := decodeEnvelope(t, invocation.stdout)
	if !envelope.OK {
		t.Fatalf("command returned non-ok envelope: %#v", envelope)
	}
}

func deterministicApp(t *testing.T, ids ...string) *App {
	t.Helper()
	app := NewApp(t.Context(), nil, nil, nil)
	app.Now = func() time.Time { return time.Date(2026, 8, 29, 12, 0, 0, 0, time.UTC) }
	if len(ids) > 0 {
		generator, _ := uuidGeneratorSequence(t, ids...)
		app.GenerateUUID = generator
	}
	return app
}

func uuidGeneratorSequence(t *testing.T, values ...string) (research.UUIDGenerator, *int) {
	t.Helper()
	parsed := make([]uuid.UUID, len(values))
	for index, value := range values {
		parsed[index] = uuid.MustParse(value)
	}
	var mutex sync.Mutex
	calls := 0
	generator := research.UUIDGenerator(func(time.Time) (uuid.UUID, error) {
		mutex.Lock()
		defer mutex.Unlock()
		if calls >= len(parsed) {
			t.Fatalf("UUID generator call %d exceeds %d configured values", calls+1, len(parsed))
		}
		value := parsed[calls]
		calls++
		return value, nil
	})
	return generator, &calls
}

func newGitRepository(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("USERPROFILE", home)
	repository := filepath.Join(t.TempDir(), "repo")
	if err := os.Mkdir(repository, 0o755); err != nil {
		t.Fatal(err)
	}
	command := exec.Command("git", "init", "--quiet")
	command.Dir = repository
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git init: %v\n%s", err, output)
	}
	canonical, err := filepath.EvalSymlinks(repository)
	if err != nil {
		t.Fatal(err)
	}
	return canonical
}

func validFixtureRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", "..", "testdata", "v1", "valid-project"))
	if err != nil {
		t.Fatal(err)
	}
	return root
}

type countingProviderRegistry struct {
	calls int
}

func (registry *countingProviderRegistry) List() []provider.Descriptor {
	registry.calls++
	return nil
}

func (registry *countingProviderRegistry) DiscoverLocal(context.Context, provider.LocalDiscoveryOptions) ([]provider.ProbeResult, error) {
	registry.calls++
	return nil, fmt.Errorf("provider discovery must not be called")
}
