// Package projection builds and publishes deterministic Markdown views from a
// validated canonical record inventory. Generated files are never read as an
// authority for records or relationships.
package projection

import (
	"crypto/sha256"
	"errors"
	"fmt"

	"github.com/daviddwlee84/exp-cli/internal/record"
)

const generatedHeader = "<!-- Generated by exp render; DO NOT EDIT. -->\n"

const (
	READMEFile    = "README.md"
	RoadmapFile   = "ROADMAP.md"
	LedgerFile    = "LEDGER.md"
	DecisionsFile = "DECISIONS.md"
)

var projectionFiles = []string{READMEFile, RoadmapFile, LedgerFile, DecisionsFile}

// Paths returns the stable publication order for generated projections.
func Paths() []string { return append([]string(nil), projectionFiles...) }

var (
	// ErrInvalidInventory means canonical diagnostics blocked projection output.
	ErrInvalidInventory = errors.New("canonical inventory is invalid")
	// ErrStale means one or more generated projections differ from canonical data.
	ErrStale = errors.New("generated projections are stale")
)

// InventoryError retains every canonical diagnostic that blocked rendering.
type InventoryError struct {
	Diagnostics []record.Diagnostic
}

func (e *InventoryError) Error() string {
	return fmt.Sprintf("%v (%d diagnostic(s))", ErrInvalidInventory, len(e.Diagnostics))
}

func (e *InventoryError) Unwrap() error { return ErrInvalidInventory }

// DriftError identifies every projection that is missing or byte-different.
type DriftError struct {
	Files []string
}

func (e *DriftError) Error() string {
	return fmt.Sprintf("%v: %v", ErrStale, e.Files)
}

func (e *DriftError) Unwrap() error { return ErrStale }

// File is one exact generated projection.
type File struct {
	Path    string
	Content []byte
}

// Build renders all four projections from one valid inventory snapshot.
func Build(inventory *record.Inventory) ([]File, error) {
	if inventory == nil {
		return nil, &InventoryError{Diagnostics: []record.Diagnostic{{Path: record.ProjectFile, Code: "project.missing", Message: "canonical inventory is nil"}}}
	}
	if !inventory.Valid() {
		return nil, &InventoryError{Diagnostics: append([]record.Diagnostic(nil), inventory.Diagnostics...)}
	}
	if inventory.Project == nil || inventory.Project.Record == nil {
		return nil, &InventoryError{Diagnostics: []record.Diagnostic{{Path: record.ProjectFile, Code: "project.missing", Message: "canonical inventory has no Project record"}}}
	}

	view, err := newView(inventory)
	if err != nil {
		return nil, err
	}
	files := []File{
		{Path: READMEFile, Content: []byte(view.readme())},
		{Path: RoadmapFile, Content: []byte(view.roadmap())},
		{Path: LedgerFile, Content: []byte(view.ledger())},
		{Path: DecisionsFile, Content: []byte(view.decisions())},
	}
	for index := range files {
		files[index].Content = append([]byte(nil), files[index].Content...)
	}
	return files, nil
}

func digest(content []byte) string {
	sum := sha256.Sum256(content)
	return fmt.Sprintf("sha256:%x", sum[:])
}
